model = "Pod"

[cameras.eo_p]
preset = "eo_4k_49deg"
yaw_deg = -40.0
pitch_deg = -10.0

[cameras.eo_c]
preset = "eo_4k_49deg"
yaw_deg = 0.0
pitch_deg = -10.0

[cameras.eo_s]
preset = "eo_4k_49deg"
yaw_deg = 40.0
pitch_deg = -10.0

[cameras.ir]
preset = "ir_vga_24deg"
pitch_deg = -6.0
